#!/usr/bin/env bash

declare -a arr=("1" "2" "3" "4")

## now loop through the above array
for i in "${arr[@]}"
do
    echo "wweb$i"
      if [ $i -lt "3" ]
      then
        scp dplagnt@wweb$i.int:/data/log/httpd/custom_access_log /data/logs/web$i/
        scp dplagnt@wweb$i.int:/data/log/httpd/custom_error_log /data/logs/web$i/
        scp dplagnt@wweb$i.int:/data/log/httpd/homepage_access_log /data/logs/web$i/
        scp dplagnt@wweb$i.int:/data/log/httpd/homepage_error_log /data/logs/web$i/
      else
        scp dplagnt@wweb$i.int:/data/log/httpd/express_access_log /data/logs/web$i/
        scp dplagnt@wweb$i.int:/data/log/httpd/express_error_log /data/logs/web$i/
      fi


    scp dplagnt@wweb$i.int:/data/log/drupal.log /data/logs/web$i/
    scp dplagnt@wweb$i.int:/data/log/drupal-auth.log /data/logs/web$i/
done

